'use strict';
const $=id=>document.getElementById(id);let APP=null,STOP=false;
const rnd=()=>Math.random(),argmin=a=>a.reduce((bi,x,i)=>x<a[bi]?i:bi,0),argmax=a=>a.reduce((bi,x,i)=>x>a[bi]?i:bi,0),mean=a=>a.reduce((s,x)=>s+x,0)/Math.max(1,a.length);
function randn(){let u=0,v=0;while(!u)u=rnd();while(!v)v=rnd();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function nums(s){return s.split(/[ ,;\n\t]+/).filter(Boolean).map(Number)}function probs(a){let s=a.reduce((x,y)=>x+y,0)||1;return a.map(x=>x/s)}function pct(a,p){let b=[...a].sort((x,y)=>x-y);return b[Math.min(b.length-1,Math.floor(p*(b.length-1)))]}function fmt(x){return Number.isFinite(x)?x.toFixed(3):''}function log(s){$('log').textContent=new Date().toLocaleTimeString()+'  '+s+'\n'+$('log').textContent}function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function cfg(){let p=nums($('processingTimes').value),pp=probs(nums($('processingProbs').value)),T=+$('numTypes').value,tp=probs(nums($('typeProbs').value));if(p.length!==pp.length)throw Error('Processing times and probabilities must have equal length.');if(tp.length!==T)tp=Array(T).fill(1/T);return{M:+$('numMachines').value,N:+$('numJobs').value,p,pp,T,tp,cm:$('changeoverMode').value,custom:$('customMatrix').value,reward:$('rewardMode').value,B:+$('batchSize').value,lr:+$('learningRate').value,H:+$('hiddenSize').value,ent:+$('entropyCoef').value,U:+$('updatesPerRun').value,evalN:+$('snapshotEvalEpisodes').value,snapWin:+$('snapshotMinWinRate').value,snapImp:+$('snapshotMinAvgImprovement').value,snapEvery:+$('snapshotInterval').value}}
function choose(vals,ps){let r=rnd(),s=0;for(let i=0;i<vals.length;i++){s+=ps[i];if(r<=s)return vals[i]}return vals.at(-1)}
function change(c){let m=Array.from({length:c.T},()=>Array(c.T).fill(0));if(c.cm==='custom'){let rows=c.custom.trim().split(/\n+/).map(nums);if(rows.length!==c.T||rows.some(r=>r.length!==c.T))throw Error('Custom matrix must be square with Job types rows and columns.');return rows}if(c.cm==='structured')for(let i=0;i<c.T;i++)for(let j=0;j<c.T;j++)m[i][j]=i===j?0:Math.floor(i/2)===Math.floor(j/2)?2:8;return m}
function stats(c,co){return{avgP:c.p.reduce((s,x,i)=>s+x*c.pp[i],0),maxP:Math.max(...c.p),avgCo:mean(co.flat()),exp:c.N*c.p.reduce((s,x,i)=>s+x*c.pp[i],0)/c.M}}
function jobs(c){return Array.from({length:c.N},()=>({p:choose(c.p,c.pp),type:choose([...Array(c.T).keys()],c.tp)}))}
function state(c,s,co,js,t,loads,last){let j=js[t],rem=js.slice(t+1),pc=Array(c.p.length).fill(0),tc=Array(c.T).fill(0),rt=0;for(let x of rem){pc[c.p.indexOf(x.p)]++;tc[x.type]++;rt+=x.p}let x=[j.p/s.maxP,j.type/Math.max(1,c.T-1),rt/Math.max(1,c.N*s.avgP),rem.length/c.N];for(let L of loads)x.push(L/Math.max(1,s.exp));for(let m=0;m<c.M;m++)x.push(last[m]<0?0:(last[m]+1)/c.T);for(let m=0;m<c.M;m++)x.push((last[m]<0?0:co[last[m]][j.type])/Math.max(1,s.avgCo,s.maxP));for(let v of pc)x.push(v/c.N);for(let v of tc)x.push(v/c.N);return x}
function soft(z){let mx=Math.max(...z),e=z.map(v=>Math.exp(v-mx)),s=e.reduce((a,b)=>a+b,0);return e.map(v=>v/s)}
class Net{constructor(I,H,O){this.I=I;this.H=H;this.O=O;this.t=0;this.W1=Array.from({length:H},()=>Array.from({length:I},()=>randn()*Math.sqrt(2/I)));this.b1=Array(H).fill(0);this.W2=Array.from({length:O},()=>Array.from({length:H},()=>randn()*Math.sqrt(2/H)));this.b2=Array(O).fill(0);this.m=this.zero();this.v=this.zero()}clone(){let n=new Net(this.I,this.H,this.O);for(let k of ['W1','b1','W2','b2'])n[k]=JSON.parse(JSON.stringify(this[k]));return n}zero(){return{W1:Array.from({length:this.H},()=>Array(this.I).fill(0)),b1:Array(this.H).fill(0),W2:Array.from({length:this.O},()=>Array(this.H).fill(0)),b2:Array(this.O).fill(0)}}f(x){let h=this.W1.map((r,i)=>Math.max(0,r.reduce((s,w,j)=>s+w*x[j],this.b1[i]))),z=this.W2.map((r,i)=>r.reduce((s,w,j)=>s+w*h[j],this.b2[i])),p=soft(z);return{p,cache:{x,h,p}}}grad(g,c,a,adv,ent){let dz=c.p.slice();dz[a]-=1;for(let k=0;k<dz.length;k++)dz[k]*=-adv; if(ent>0){let lp=c.p.map(v=>Math.log(v+1e-9)),E=-c.p.reduce((s,v,i)=>s+v*lp[i],0);for(let k=0;k<dz.length;k++)dz[k]-=ent*c.p[k]*(-lp[k]-E)}let dh=Array(this.H).fill(0);for(let o=0;o<this.O;o++){g.b2[o]+=dz[o];for(let h=0;h<this.H;h++){g.W2[o][h]+=dz[o]*c.h[h];dh[h]+=this.W2[o][h]*dz[o]}}for(let h=0;h<this.H;h++){if(c.h[h]<=0)dh[h]=0;g.b1[h]+=dh[h];for(let i=0;i<this.I;i++)g.W1[h][i]+=dh[h]*c.x[i]}}step(g,lr,scale){this.t++;let b1=.9,b2=.999,eps=1e-8;for(let K of ['W1','b1','W2','b2']){let upd=(arr,gr,m,v)=>{for(let i=0;i<arr.length;i++)Array.isArray(arr[i])?upd(arr[i],gr[i],m[i],v[i]):(gr[i]*=scale,m[i]=b1*m[i]+(1-b1)*gr[i],v[i]=b2*v[i]+(1-b2)*gr[i]*gr[i],arr[i]-=lr*(m[i]/(1-b1**this.t))/(Math.sqrt(v[i]/(1-b2**this.t))+eps))};upd(this[K],g[K],this.m[K],this.v[K])}}}
function runNet(net,c,s,co,js,det,learn){let loads=Array(c.M).fill(0),last=Array(c.M).fill(-1),traj=[];for(let t=0;t<js.length;t++){let x=state(c,s,co,js,t,loads,last),o=net.f(x),a=det?argmax(o.p):sample(o.p);if(learn)traj.push({cache:o.cache,a});let add=last[a]<0?0:co[last[a]][js[t].type];loads[a]+=js[t].p+add;last[a]=js[t].type}return{makespan:Math.max(...loads),traj}}
function sample(p){let r=rnd(),s=0;for(let i=0;i<p.length;i++){s+=p[i];if(r<=s)return i}return p.length-1}
function base(kind,c,co,js){let xs=kind==='lpt_reference'?[...js].sort((a,b)=>b.p-a.p):js,loads=Array(c.M).fill(0),last=Array(c.M).fill(-1);for(let j of xs){let a=0;if(kind==='random')a=Math.floor(rnd()*c.M);else if(kind==='load_list')a=argmin(loads);else{let best=Infinity;for(let m=0;m<c.M;m++){let v=loads[m]+j.p+(last[m]<0?0:co[last[m]][j.type]);if(v<best)best=v,a=m}}loads[a]+=j.p+(last[a]<0?0:co[last[a]][j.type]);last[a]=j.type}return Math.max(...loads)}
function reward(mode,cur,prev){if(cur===prev)return 0;let d=prev-cur;return mode==='win_loss'?(d>0?1:-1):mode==='difference'?d:d/Math.max(1,prev)}
function init(){let c=cfg(),co=change(c),s=stats(c,co),js=jobs(c),x=state(c,s,co,js,0,Array(c.M).fill(0),Array(c.M).fill(-1)),net=new Net(x.length,c.H,c.M);APP={c,co,s,cur:net,prev:net.clone(),gen:0,upd:0,hist:[],last:null};$('status').textContent=`Initialized. Input dim ${x.length}. Generation 0, update 0.`;$('metricsTable').querySelector('tbody').innerHTML='';draw();log(`Initialized: ${c.M} machines, ${c.N} jobs, changeover=${c.cm}.`)}
async function train(){if(!APP)init();STOP=false;let nc=cfg();Object.assign(APP.c,{reward:nc.reward,B:nc.B,lr:nc.lr,ent:nc.ent,U:nc.U,evalN:nc.evalN,snapWin:nc.snapWin,snapImp:nc.snapImp,snapEvery:nc.snapEvery});for(let u=0;u<APP.c.U&&!STOP;u++){let eps=[];for(let b=0;b<APP.c.B;b++){let js=jobs(APP.c),cu=runNet(APP.cur,APP.c,APP.s,APP.co,js,false,true),pr=runNet(APP.prev,APP.c,APP.s,APP.co,js,false,false),r=reward(APP.c.reward,cu.makespan,pr.makespan);eps.push({r,tr:cu.traj})}let rs=eps.map(e=>e.r),m=mean(rs),sd=Math.sqrt(mean(rs.map(r=>(r-m)**2)))||1,g=APP.cur.zero(),steps=0;for(let e of eps)for(let st of e.tr){APP.cur.grad(g,st.cache,st.a,(e.r-m)/sd,APP.c.ent);steps++}APP.cur.step(g,APP.c.lr,1/Math.max(1,steps));APP.upd++;if(APP.upd%APP.c.snapEvery===0){let q=cmp(APP.cur,APP.prev,APP.c.evalN),ok=q.win>=APP.c.snapWin&&q.imp>=APP.c.snapImp;APP.hist.push({update:APP.upd,generation:APP.gen,selfPlayWinRate:q.win,selfPlayAvgImprovement:q.imp});if(ok){APP.prev=APP.cur.clone();APP.gen++;log(`Snapshot accepted: generation ${APP.gen}, win ${(100*q.win).toFixed(1)}%, avg improvement ${(100*q.imp).toFixed(2)}%.`)}else log(`Snapshot rejected: win ${(100*q.win).toFixed(1)}%, avg improvement ${(100*q.imp).toFixed(2)}%.`);draw();await sleep(0)}if(APP.upd%5===0)$('status').textContent=`Training. Update ${APP.upd}, generation ${APP.gen}.`;if(APP.upd%10===0)await sleep(0)}$('status').textContent=`Stopped. Update ${APP.upd}, generation ${APP.gen}.`}
function cmp(a,b,n){let w=0,im=[];for(let i=0;i<n;i++){let js=jobs(APP.c),am=runNet(a,APP.c,APP.s,APP.co,js,true,false).makespan,bm=runNet(b,APP.c,APP.s,APP.co,js,true,false).makespan;if(am<bm)w++;im.push((bm-am)/Math.max(1,bm))}return{win:w/n,imp:mean(im)}}
function evaluate(n=1000){if(!APP)init();let ks=['random','load_list','cost_greedy','nn','lpt_reference'],rows=Object.fromEntries(ks.map(k=>[k,[]])),wll=Object.fromEntries(ks.map(k=>[k,0])),wcg=Object.fromEntries(ks.map(k=>[k,0]));for(let i=0;i<n;i++){let js=jobs(APP.c),v={random:base('random',APP.c,APP.co,js),load_list:base('load_list',APP.c,APP.co,js),cost_greedy:base('cost_greedy',APP.c,APP.co,js),nn:runNet(APP.cur,APP.c,APP.s,APP.co,js,true,false).makespan,lpt_reference:base('lpt_reference',APP.c,APP.co,js)};for(let k of ks){rows[k].push(v[k]);if(v[k]<v.load_list)wll[k]++;if(v[k]<v.cost_greedy)wcg[k]++}}let names={random:'Random',load_list:'Load-only list',cost_greedy:'Cost-aware greedy',nn:'NN policy',lpt_reference:'Offline p-desc greedy ref'},tb=$('metricsTable').querySelector('tbody');tb.innerHTML='';let summary=[];for(let k of ks){let xs=rows[k],it={method:names[k],mean:mean(xs),median:pct(xs,.5),p90:pct(xs,.9),p95:pct(xs,.95),winVsLoadList:wll[k]/n,winVsCostGreedy:wcg[k]/n};summary.push(it);let tr=document.createElement('tr');tr.innerHTML=`<td>${it.method}</td><td>${fmt(it.mean)}</td><td>${fmt(it.median)}</td><td>${fmt(it.p90)}</td><td>${fmt(it.p95)}</td><td>${(100*it.winVsLoadList).toFixed(1)}%</td><td>${(100*it.winVsCostGreedy).toFixed(1)}%</td>`;tb.appendChild(tr)}APP.last={n,summary,update:APP.upd,generation:APP.gen,cfg:APP.c,changeover:APP.co};$('status').textContent=`Evaluated ${n} instances. Update ${APP.upd}, generation ${APP.gen}.`;let nn=summary.find(x=>x.method==='NN policy'),ll=summary.find(x=>x.method==='Load-only list'),cg=summary.find(x=>x.method==='Cost-aware greedy');log(`Evaluation: NN mean ${fmt(nn.mean)}, load-list ${fmt(ll.mean)}, cost-greedy ${fmt(cg.mean)}.`)}
function draw(){let c=$('chart'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.font='13px system-ui';ctx.fillText('Self-play validation over time',16,22);if(!APP||APP.hist.length<2){ctx.fillText('Train to populate chart.',16,48);return}let p=42,W=c.width-2*p,H=c.height-2*p;ctx.strokeRect(p,p,W,H);let xs=APP.hist.map(h=>h.update),min=Math.min(...xs),max=Math.max(...xs),px=x=>p+(x-min)/Math.max(1,max-min)*W,py=y=>p+H-y*H;ctx.beginPath();APP.hist.forEach((h,i)=>i?ctx.lineTo(px(h.update),py(h.selfPlayWinRate)):ctx.moveTo(px(h.update),py(h.selfPlayWinRate)));ctx.stroke();ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(p,py(APP.c.snapWin));ctx.lineTo(p+W,py(APP.c.snapWin));ctx.stroke();ctx.setLineDash([]);ctx.fillText('win rate vs previous generation',p,c.height-12);ctx.fillText('threshold',p+W-75,py(APP.c.snapWin)-6)}
function dl(){if(!APP)return;let blob=new Blob([JSON.stringify({history:APP.hist,lastEval:APP.last,generation:APP.gen,update:APP.upd},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='job-scheduling-rl-results.json';a.click();URL.revokeObjectURL(u)}
$('initBtn').onclick=()=>{try{init()}catch(e){alert(e.message)}};$('trainBtn').onclick=()=>train().catch(e=>alert(e.message));$('stopBtn').onclick=()=>{STOP=true};$('evalBtn').onclick=()=>evaluate(1000);$('downloadBtn').onclick=dl;window.onload=()=>{try{init();evaluate(300)}catch(e){log(e.message)}};
